### PR TITLE
* Enable accounts more than usual private/key pairs

### PR DESCRIPTION
**Pull request by shawnpringle**
Each account can more than one key-pairs for a given role.  An active role may have several public keys registered to it.  This pull request sets Keychain to allow any of these.   Also, the keys can be setup so that a password will yield a good posting key but not a good active, owner or memo key.  You may want to do this if you are a blogger who uses random public computers for blogging and would like to keep a password insecure enough to be memorable.  Such an improper password will also work with these changes.

### CODE REVIEW

**Comment by stoodkev** [comment]
Sorry for the (very) late answer, I haven t checked the PRs for a while.
Could you please resolve the conflicts and I ll be happy to check and implement it. 
Thanks!

**Comment by shawnpringle** [comment]
My fork works fine on my box.  If you like my changes, you are welcome to fix the conflicts, yourself.  :)

**Comment by shawnpringle** [comment]
Okay!  I have fixed the conflicts.  I invite you to pull my latest commit fd061c it into the master branch.

**Comment by shawnpringle** [comment]
Related issues are #122 and #109.  These other issues will require changes to the data structures used I think.

**Comment by stoodkev** [comment]
Thanks! I will review this in the coming days and also work on adding accounts via other accounts' authority.

**Pull request merged**
